# Regression. Part 2

---
Author: Durkin Anatoliy

Updated: 31.03.2025

---
В данном ноутбуке ...

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [2]:
def metrics(true, pred):
    print('R2:', r2_score(true, pred))
    print('MAE:', mean_absolute_error(true, pred))
    print('RMSE:', mean_squared_error(true, pred)**0.5)

In [3]:
df = pd.read_csv('house_price_regression_dataset.csv')

In [4]:
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

In [6]:
df.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,2.990000,1.973000,1986.550000,2.778087,1.022000,5.615000,6.188610e+05
std,1255.514921,1.427564,0.820332,20.632916,1.297903,0.814973,2.887059,2.535681e+05
min,503.000000,1.000000,1.000000,1950.000000,0.506058,0.000000,1.000000,1.116269e+05
25%,1749.500000,2.000000,1.000000,1969.000000,1.665946,0.000000,3.000000,4.016482e+05
50%,2862.500000,3.000000,2.000000,1986.000000,2.809740,1.000000,6.000000,6.282673e+05
75%,3849.500000,4.000000,3.000000,2004.250000,3.923317,2.000000,8.000000,8.271413e+05
max,4999.000000,5.000000,3.000000,2022.000000,4.989303,2.000000,10.000000,1.108237e+06

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['House_Price'], axis=1), df['House_Price'], test_size=0.2, random_state=42)

# Модели

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
lr = LinearRegression().fit(X_train, y_train)

In [10]:
metrics(y_test, lr.predict(X_test))

R2: 0.9984263636823408
MAE: 8174.583600008765
RMSE: 10071.48442413872

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
rf = RandomForestRegressor().fit(X_train, y_train)

In [13]:
metrics(y_test, rf.predict(X_test))

R2: 0.99402317878735
MAE: 16030.063743676477
RMSE: 19628.017331764568

In [14]:
from sklearn.ensemble import GradientBoostingRegressor

In [15]:
gbr = GradientBoostingRegressor().fit(X_train, y_train)

In [16]:
metrics(y_test, gbr.predict(X_test))

R2: 0.9965087150085455
MAE: 12307.185036973111
RMSE: 15001.474604564883

In [17]:
!pip install catboost --default-timeout=100

Requirement already satisfied: catboost in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (1.2.10)
Requirement already satisfied: graphviz in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (3.10.8)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (2.4.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (3.0.1)
Requirement already satisfied: scipy in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (1.17.1)
Requirement already satisfied: plotly in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (6.6.0)
Requirement already satisfied: six in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from plotly->catboost) (2.18.0)

In [18]:
from catboost import CatBoostRegressor

In [19]:
cb = CatBoostRegressor().fit(X_train, y_train, verbose=False)

In [20]:
metrics(y_test, cb.predict(X_test))

R2: 0.9976469255147913
MAE: 9687.789728016342
RMSE: 12315.701033854577

# Отбор признаков

## Прямой отбор

In [21]:
from sklearn.feature_selection import SequentialFeatureSelector

In [22]:
cb = CatBoostRegressor(verbose=False)
sfs = SequentialFeatureSelector(cb, direction='forward')
sfs.fit(X_train, y_train)

SequentialFeatureSelector(estimator=CatBoostRegressor(loss_function='RMSE', verbose=False))

In [23]:
sfs.get_support()

array([ True, False, False,  True,  True, False, False])

In [24]:
sfs.get_params()

{'cv': 5,
 'direction': 'forward',
 'estimator__loss_function': 'RMSE',
 'estimator__verbose': False,
 'estimator': CatBoostRegressor(loss_function='RMSE', verbose=False),
 'n_features_to_select': 'auto',
 'n_jobs': None,
 'scoring': None,
 'tol': None}

In [25]:
sfs.transform(X_test)

array([[4.01200000e+03, 2.01600000e+03, 2.09809241e+00],
       [2.31000000e+03, 1.98800000e+03, 1.36962237e+00],
       [4.70800000e+03, 1.96200000e+03, 1.79297022e+00],
       [4.93200000e+03, 1.97200000e+03, 4.47959818e+00],
       [3.64600000e+03, 1.99400000e+03, 3.98098734e+00],
       [3.58600000e+03, 1.96400000e+03, 2.56842869e+00],
       [4.63800000e+03, 2.00000000e+03, 1.49039905e+00],
       [4.12700000e+03, 1.99200000e+03, 1.02615591e+00],
       [3.78100000e+03, 1.98900000e+03, 3.16407579e+00],
       [4.24300000e+03, 2.00200000e+03, 4.49808849e+00],
       [3.61000000e+03, 1.97900000e+03, 3.43441878e+00],
       [3.06800000e+03, 1.98600000e+03, 2.07591346e+00],
       [7.80000000e+02, 2.00800000e+03, 2.59075926e+00],
       [4.92500000e+03, 1.95900000e+03, 4.89664254e+00],
       [2.56500000e+03, 2.00400000e+03, 1.03802899e+00],
       [8.85000000e+02, 1.96000000e+03, 1.79713210e+00],
       [2.18600000e+03, 1.97800000e+03, 5.39177662e-01],
       [1.70500000e+03, 1.97700000e+03, 1.96620557e+00],
       [3.33200000e+03, 1.99000000e+03, 3.13177384e+00],
       [1.37600000e+03, 1.98600000e+03, 3.48890771e+00],
       [3.45600000e+03, 2.01400000e+03, 4.05271534e+00],
       [2.29400000e+03, 1.96800000e+03, 1.09690060e+00],
       [3.31600000e+03, 1.98400000e+03, 6.13568056e-01],
       [4.13700000e+03, 1.97600000e+03, 4.42858727e+00],
       [1.94500000e+03, 1.99400000e+03, 8.14102946e-01],
       [1.45400000e+03, 2.00200000e+03, 3.83254125e+00],
       [1.98400000e+03, 1.95700000e+03, 4.37681168e+00],
       [1.90900000e+03, 1.95800000e+03, 4.65848472e+00],
       [9.17000000e+02, 1.95300000e+03, 5.61353108e-01],
       [1.98100000e+03, 1.98400000e+03, 3.95374474e+00],
       [1.08000000e+03, 1.97700000e+03, 2.31249125e+00],
       [4.26300000e+03, 1.95300000e+03, 4.36154177e+00],
       [3.53100000e+03, 1.99900000e+03, 1.79602406e+00],
       [1.39400000e+03, 1.98300000e+03, 4.35259625e+00],
       [2.13100000e+03, 1.95900000e+03, 4.94834742e+00],
       [3.60800000e+03, 1.97200000e+03, 4.72969306e+00],
       [2.10300000e+03, 1.98300000e+03, 3.99330715e+00],
       [2.58100000e+03, 1.98900000e+03, 4.01677541e+00],
       [9.74000000e+02, 2.00600000e+03, 4.51040033e+00],
       [6.61000000e+02, 1.96400000e+03, 2.18516180e+00],
       [1.33000000e+03, 1.96200000e+03, 2.61890310e+00],
       [1.00200000e+03, 2.00000000e+03, 3.70749954e+00],
       [2.21500000e+03, 1.96600000e+03, 3.71833905e+00],
       [1.27400000e+03, 1.98500000e+03, 2.95147502e+00],
       [4.99500000e+03, 2.00700000e+03, 3.68003990e+00],
       [4.36300000e+03, 2.01800000e+03, 4.93386725e+00],
       [3.71200000e+03, 1.96100000e+03, 8.94424263e-01],
       [3.77800000e+03, 2.00600000e+03, 1.57614145e+00],
       [4.67100000e+03, 2.01700000e+03, 1.93122308e+00],
       [3.39100000e+03, 1.97700000e+03, 1.45550288e+00],
       [1.01000000e+03, 1.97200000e+03, 4.53147882e+00],
       [3.36100000e+03, 2.02200000e+03, 1.64136000e+00],
       [3.67000000e+03, 2.01200000e+03, 2.06378187e+00],
       [3.22400000e+03, 1.96400000e+03, 4.60801600e+00],
       [2.30600000e+03, 2.01400000e+03, 3.63773939e+00],
       [3.70200000e+03, 1.98400000e+03, 2.89209829e+00],
       [6.37000000e+02, 1.99000000e+03, 2.89247461e+00],
       [1.26900000e+03, 2.00600000e+03, 3.55503976e+00],
       [3.36900000e+03, 1.96200000e+03, 3.58427905e+00],
       [9.19000000e+02, 1.98500000e+03, 1.10786066e+00],
       [4.61500000e+03, 2.00000000e+03, 1.72114684e+00],
       [1.52100000e+03, 2.01300000e+03, 2.50874101e+00],
       [1.03900000e+03, 2.00700000e+03, 4.53064083e+00],
       [2.14800000e+03, 1.98300000e+03, 4.88411444e+00],
       [2.62200000e+03, 2.01900000e+03, 6.98181707e-01],
       [2.65800000e+03, 1.95500000e+03, 3.75904646e+00],
       [1.77600000e+03, 2.00600000e+03, 4.22819660e+00],
       [3.43500000e+03, 1.96500000e+03, 4.10092856e+00],
       [4.49300000e+03, 2.00800000e+03, 9.66553613e-01],
       [3.27900000e+03, 1.97500000e+03, 4.02575036e+00],
       [2.17800000e+03, 2.01300000e+03, 1.10142762e+00],
       [4.02200000e+03, 1.95300000e+03, 4.73689810e+00],
       [1.27000000e+03, 1.95300000e+03, 2.39342541e+00],
       [2.54800000e+03, 2.00300000e+03, 1.75885685e+00],
       [2.95500000e+03, 1.96200000e+03, 4.54207129e+00],
       [3.30600000e+03, 2.01700000e+03, 1.86115563e+00],
       [2.25300000e+03, 2.01200000e+03, 3.95657680e+00],
       [7.41000000e+02, 1.99700000e+03, 1.76396884e+00],
       [2.66500000e+03, 1.97300000e+03, 8.44557163e-01],
       [4.23600000e+03, 1.97000000e+03, 1.28409531e+00],
       [2.57500000e+03, 1.98100000e+03, 2.43942756e+00],
       [1.51600000e+03, 2.01700000e+03, 4.29046477e+00],
       [2.39500000e+03, 1.99000000e+03, 2.47305522e+00],
       [8.37000000e+02, 1.96700000e+03, 2.17958520e+00],
       [5.04000000e+02, 1.96100000e+03, 4.96297796e+00],
       [1.42400000e+03, 1.95400000e+03, 4.42898979e+00],
       [4.72300000e+03, 1.95000000e+03, 1.93092148e+00],
       [4.01700000e+03, 2.01600000e+03, 4.76040216e+00],
       [2.17300000e+03, 1.97800000e+03, 4.59861202e+00],
       [6.19000000e+02, 2.02000000e+03, 2.85242064e+00],
       [4.24600000e+03, 2.01400000e+03, 1.69416550e+00],
       [3.72200000e+03, 1.97500000e+03, 3.44022574e+00],
       [1.75600000e+03, 1.96200000e+03, 7.03621351e-01],
       [3.46100000e+03, 2.00900000e+03, 2.53809982e+00],
       [3.39800000e+03, 1.98300000e+03, 1.26077800e+00],
       [4.99200000e+03, 1.96000000e+03, 4.25779675e+00],
       [3.45800000e+03, 1.99800000e+03, 1.60933958e+00],
       [4.14500000e+03, 1.99300000e+03, 3.22435291e+00],
       [3.84200000e+03, 1.99100000e+03, 4.68179781e+00],
       [2.83600000e+03, 1.98100000e+03, 5.06058219e-01],
       [4.23500000e+03, 2.00000000e+03, 1.91167930e+00],
       [4.00600000e+03, 2.00300000e+03, 1.09244115e+00],
       [7.85000000e+02, 1.99500000e+03, 3.82327645e+00],
       [2.82700000e+03, 1.97700000e+03, 3.21367800e+00],
       [2.21900000e+03, 1.96500000e+03, 7.25964943e-01],
       [4.65600000e+03, 1.95900000e+03, 2.29202507e+00],
       [2.33800000e+03, 2.01800000e+03, 4.07106795e+00],
       [8.27000000e+02, 1.96200000e+03, 3.43355390e+00],
       [1.10800000e+03, 1.98400000e+03, 1.90488366e+00],
       [4.74300000e+03, 2.01600000e+03, 2.25454886e+00],
       [3.83000000e+03, 1.98300000e+03, 2.85414359e+00],
       [1.62000000e+03, 1.98500000e+03, 4.74767728e+00],
       [4.09400000e+03, 2.02100000e+03, 3.79574801e+00],
       [2.53500000e+03, 2.01700000e+03, 7.74532144e-01],
       [3.60400000e+03, 1.99500000e+03, 1.21405493e+00],
       [4.45200000e+03, 1.97500000e+03, 3.43182057e+00],
       [9.88000000e+02, 1.98600000e+03, 3.54256429e+00],
       [4.19500000e+03, 1.96000000e+03, 4.58480945e+00],
       [8.57000000e+02, 1.98400000e+03, 1.64271997e+00],
       [3.45000000e+03, 2.01900000e+03, 8.44159800e-01],
       [7.01000000e+02, 2.00900000e+03, 4.16045517e+00],
       [2.18700000e+03, 1.98100000e+03, 1.35112595e+00],
       [3.92100000e+03, 2.00500000e+03, 3.79020805e+00],
       [1.10600000e+03, 1.97900000e+03, 1.07571616e+00],
       [1.54500000e+03, 1.97000000e+03, 3.17337251e+00],
       [1.51500000e+03, 1.97500000e+03, 1.02065593e+00],
       [2.32300000e+03, 1.97600000e+03, 3.92847625e+00],
       [4.07700000e+03, 2.00300000e+03, 1.81632391e+00],
       [4.37600000e+03, 1.99700000e+03, 4.38354071e+00],
       [2.69000000e+03, 2.01700000e+03, 6.05896225e-01],
       [3.31400000e+03, 2.01100000e+03, 4.30188047e+00],
       [3.09700000e+03, 1.98900000e+03, 4.28907048e+00],
       [2.80000000e+03, 1.96100000e+03, 4.51351896e+00],
       [3.26100000e+03, 1.97800000e+03, 2.16511036e+00],
       [3.20300000e+03, 1.95000000e+03, 3.64860459e+00],
       [3.96100000e+03, 2.00000000e+03, 8.15015805e-01],
       [2.48100000e+03, 1.96100000e+03, 1.75305896e+00],
       [3.05700000e+03, 1.96600000e+03, 1.41874952e+00],
       [3.23400000e+03, 1.96900000e+03, 2.59274862e+00],
       [9.92000000e+02, 1.96600000e+03, 3.11456792e+00],
       [1.97800000e+03, 1.99900000e+03, 3.84386693e+00],
       [3.62000000e+03, 2.01100000e+03, 4.89284139e+00],
       [1.56300000e+03, 1.97600000e+03, 5.28158620e-01],
       [3.50900000e+03, 1.97700000e+03, 1.20007147e+00],
       [4.00700000e+03, 1.98900000e+03, 4.65914424e+00],
       [1.46600000e+03, 1.95400000e+03, 3.49820538e+00],
       [4.51800000e+03, 1.97100000e+03, 1.37754041e+00],
       [1.45900000e+03, 2.00400000e+03, 3.60805897e+00],
       [3.09700000e+03, 1.95900000e+03, 4.50309478e+00],
       [4.64200000e+03, 1.96600000e+03, 7.02326487e-01],
       [2.46900000e+03, 1.96000000e+03, 4.01433739e+00],
       [3.75500000e+03, 1.99200000e+03, 2.59621589e+00],
       [4.74200000e+03, 1.97700000e+03, 8.35872940e-01],
       [4.26600000e+03, 2.00800000e+03, 1.39928572e+00],
       [4.78900000e+03, 1.99800000e+03, 4.11843051e+00],
       [3.03900000e+03, 1.99500000e+03, 2.94359644e+00],
       [1.07400000e+03, 1.98200000e+03, 2.48785921e+00],
       [3.16000000e+03, 1.97600000e+03, 1.21831206e+00],
       [4.79700000e+03, 1.97900000e+03, 2.16266870e+00],
       [3.53000000e+03, 2.00300000e+03, 1.07498594e+00],
       [7.35000000e+02, 2.00200000e+03, 3.44372069e+00],
       [4.17700000e+03, 1.95200000e+03, 2.01789929e+00],
       [3.61700000e+03, 1.97400000e+03, 4.74428670e+00],
       [3.09300000e+03, 1.97000000e+03, 1.56715010e+00],
       [4.95100000e+03, 1.98200000e+03, 1.07368556e+00],
       [4.62300000e+03, 1.95500000e+03, 4.35736246e+00],
       [4.34700000e+03, 1.96600000e+03, 4.23191405e+00],
       [7.32000000e+02, 1.95300000e+03, 3.04438985e+00],
       [2.99100000e+03, 1.99600000e+03, 2.13714339e+00],
       [3.76100000e+03, 1.97300000e+03, 4.92905525e+00],
       [2.97900000e+03, 1.99300000e+03, 2.17026282e+00],
       [1.01000000e+03, 1.99000000e+03, 3.69559688e+00],
       [2.22200000e+03, 1.99400000e+03, 4.81324026e+00],
       [2.05500000e+03, 2.01100000e+03, 1.86357878e+00],
       [2.31000000e+03, 2.01100000e+03, 7.70433847e-01],
       [2.25700000e+03, 2.00200000e+03, 1.63759300e+00],
       [3.06500000e+03, 1.96300000e+03, 1.47302154e+00],
       [4.77600000e+03, 1.97100000e+03, 3.99160190e+00],
       [3.21200000e+03, 1.97500000e+03, 1.75522134e+00],
       [2.40600000e+03, 2.01600000e+03, 1.36009440e+00],
       [4.76800000e+03, 1.97800000e+03, 4.02892778e+00],
       [3.78700000e+03, 1.95200000e+03, 2.48258088e+00],
       [1.39500000e+03, 1.97300000e+03, 3.30565024e+00],
       [1.89600000e+03, 2.00300000e+03, 9.76339561e-01],
       [2.61600000e+03, 1.99200000e+03, 1.06873890e+00],
       [1.99500000e+03, 2.00000000e+03, 4.20947101e+00],
       [1.74300000e+03, 1.96200000e+03, 2.70844253e+00],
       [2.57000000e+03, 1.96200000e+03, 4.52293342e+00],
       [2.66100000e+03, 2.00700000e+03, 2.41671969e+00],
       [1.40100000e+03, 2.01200000e+03, 2.98743066e+00],
       [2.40100000e+03, 1.98800000e+03, 1.88388408e+00],
       [2.35700000e+03, 1.99700000e+03, 5.82737640e-01],
       [4.70200000e+03, 1.96400000e+03, 2.96362170e+00],
       [4.59000000e+03, 1.95800000e+03, 2.76801694e+00],
       [7.53000000e+02, 2.01500000e+03, 4.14616364e+00],
       [3.76700000e+03, 1.98100000e+03, 1.52033533e+00],
       [6.16000000e+02, 1.96500000e+03, 3.46137163e+00],
       [4.49100000e+03, 1.99400000e+03, 3.39915526e+00],
       [1.85800000e+03, 1.99600000e+03, 4.54667162e+00],
       [3.19500000e+03, 1.96200000e+03, 3.91325846e+00]])

## Последовательный отбор

In [26]:
cb = CatBoostRegressor(verbose=False)
sfs = SequentialFeatureSelector(cb, direction='backward')
sfs.fit(X_train, y_train)

SequentialFeatureSelector(direction='backward',
                          estimator=CatBoostRegressor(loss_function='RMSE', verbose=False))

In [27]:
sfs.get_support()

array([ True,  True, False,  True,  True, False, False])

## Исчерпывающий выбор

In [28]:
!pip3 install mlxtend --default-timeout=100

Requirement already satisfied: mlxtend in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (0.24.0)
Requirement already satisfied: scipy>=1.16.3 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from mlxtend) (2.4.2)
Requirement already satisfied: pandas>=2.3.3 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from mlxtend) (3.0.1)
Requirement already satisfied: scikit-learn>=1.8.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)

In [29]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector

In [30]:
cb = CatBoostRegressor(verbose=False)
efs = ExhaustiveFeatureSelector(cb, min_features=1, max_features=7, scoring='r2', cv=5)
efs.fit(X_train, y_train)

Features: 127/127/Users/admin/Desktop/СГУ/Машинное обучение/venv_0/lib/python3.13/site-packages/sklearn/externals/_numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
----------- in
Exhaustive Feature Selection for Classification and Regression.
   (new in v0.4.3)...
  while not self._is_at_section() and not self._doc.eof():

ExhaustiveFeatureSelector(estimator=CatBoostRegressor(loss_function='RMSE', verbose=False),
                          feature_groups=[[0], [1], [2], [3], [4], [5], [6]],
                          max_features=7, scoring='r2')

In [31]:
efs.best_score_

np.float64(0.9970567314053543)

In [32]:
efs.best_feature_names_

('Square_Footage',
 'Num_Bedrooms',
 'Num_Bathrooms',
 'Year_Built',
 'Lot_Size',
 'Garage_Size')

In [33]:
efs.subsets_

{0: {'feature_idx': (0,),
  'cv_scores': array([0.97921123, 0.98034293, 0.98241054, 0.97691594, 0.9807523 ]),
  'avg_score': np.float64(0.9799265873009346),
  'feature_names': ('Square_Footage',)},
 1: {'feature_idx': (1,),
  'cv_scores': array([ 0.00075249,  0.00635901, -0.00178436,  0.00829565,  0.00756045]),
  'avg_score': np.float64(0.004236649931976077),
  'feature_names': ('Num_Bedrooms',)},
 2: {'feature_idx': (2,),
  'cv_scores': array([-0.00850559, -0.00065699, -0.00100347,  0.00019372, -0.01260056]),
  'avg_score': np.float64(-0.004514578001016578),
  'feature_names': ('Num_Bathrooms',)},
 3: {'feature_idx': (3,),
  'cv_scores': array([-0.07221276, -0.18134114, -0.08481621, -0.10551191, -0.12634343]),
  'avg_score': np.float64(-0.11404508809386323),
  'feature_names': ('Year_Built',)},
 4: {'feature_idx': (4,),
  'cv_scores': array([-0.09886572, -0.05185182, -0.06426124,  0.06371277, -0.0870423 ]),
  'avg_score': np.float64(-0.04766166076940139),
  'feature_names': ('Lot_Size',)},
 5: {'feature_idx': (5,),
  'cv_scores': array([-0.006141  ,  0.01832085, -0.03818439,  0.01371251,  0.00586541]),
  'avg_score': np.float64(-0.0012853222400587949),
  'feature_names': ('Garage_Size',)},
 6: {'feature_idx': (6,),
  'cv_scores': array([-0.00409532, -0.0131817 , -0.01864932, -0.00294236, -0.03484452]),
  'avg_score': np.float64(-0.014742643586081882),
  'feature_names': ('Neighborhood_Quality',)},
 7: {'feature_idx': (0, 1),
  'cv_scores': array([0.98211031, 0.9825413 , 0.98427687, 0.97894722, 0.98428726]),
  'avg_score': np.float64(0.9824325919267609),
  'feature_names': ('Square_Footage', 'Num_Bedrooms')},
 8: {'feature_idx': (0, 2),
  'cv_scores': array([0.98014829, 0.98005451, 0.98364675, 0.97860483, 0.98158805]),
  'avg_score': np.float64(0.9808084862484412),
  'feature_names': ('Square_Footage', 'Num_Bathrooms')},
 9: {'feature_idx': (0, 3),
  'cv_scores': array([0.98320211, 0.98570851, 0.98840133, 0.98582793, 0.98486771]),
  'avg_score': np.float64(0.9856015193070118),
  'feature_names': ('Square_Footage', 'Year_Built')},
 10: {'feature_idx': (0, 4),
  'cv_scores': array([0.98351668, 0.98626793, 0.98457293, 0.98077707, 0.98705988]),
  'avg_score': np.float64(0.984438897742705),
  'feature_names': ('Square_Footage', 'Lot_Size')},
 11: {'feature_idx': (0, 5),
  'cv_scores': array([0.97962664, 0.9796749 , 0.98074685, 0.97920161, 0.98129503]),
  'avg_score': np.float64(0.9801090073437854),
  'feature_names': ('Square_Footage', 'Garage_Size')},
 12: {'feature_idx': (0, 6),
  'cv_scores': array([0.97800172, 0.97830336, 0.98037896, 0.97395353, 0.98086644]),
  'avg_score': np.float64(0.9783007985045638),
  'feature_names': ('Square_Footage', 'Neighborhood_Quality')},
 13: {'feature_idx': (1, 2),
  'cv_scores': array([-0.01546164, -0.00599681, -0.0259909 , -0.02357169, -0.02403758]),
  'avg_score': np.float64(-0.019011722546206266),
  'feature_names': ('Num_Bedrooms', 'Num_Bathrooms')},
 14: {'feature_idx': (1, 3),
  'cv_scores': array([-0.1131689 , -0.1560139 , -0.19996985, -0.14365307, -0.17369184]),
  'avg_score': np.float64(-0.1572995144018526),
  'feature_names': ('Num_Bedrooms', 'Year_Built')},
 15: {'feature_idx': (1, 4),
  'cv_scores': array([-0.14936834, -0.05758187, -0.12270795, -0.01336941, -0.09429889]),
  'avg_score': np.float64(-0.08746529247562793),
  'feature_names': ('Num_Bedrooms', 'Lot_Size')},
 16: {'feature_idx': (1, 5),
  'cv_scores': array([-0.0902253 ,  0.02108732, -0.04681972,  0.01033095, -0.01887302]),
  'avg_score': np.float64(-0.02489995337427975),
  'feature_names': ('Num_Bedrooms', 'Garage_Size')},
 17: {'feature_idx': (1, 6),
  'cv_scores': array([-0.10577919, -0.0667256 , -0.11325185, -0.16503975, -0.13653468]),
  'avg_score': np.float64(-0.11746621536875365),
  'feature_names': ('Num_Bedrooms', 'Neighborhood_Quality')},
 18: {'feature_idx': (2, 3),
  'cv_scores': array([-0.15111668, -0.22696498, -0.14585802, -0.09616622, -0.11478586]),
  'avg_score': np.float64(-0.14697835112166402),
  'feature_names': ('Num_Bathrooms', 'Year_Built')},
 19: {'feature_idx': (2, 4),
  'cv_scores': array([-0.15633188, -0.07051856, -0.0476604 ,  0.00693144, -0.11793697]),
  'avg_score': np.float64(-0.07710327202155383),
  'feature_names': ('Num_Bathrooms', 'Lot_Size')},
 20: {'feature_idx': (2, 5),
  'cv_scores': array([-0.01575199, -0.00656396, -0.04812219,  0.00973507, -0.03740832]),
  'avg_score': np.float64(-0.0196222782034295),
  'feature_names': ('Num_Bathrooms', 'Garage_Size')},
 21: {'feature_idx': (2, 6),
  'cv_scores': array([ 0.01658804, -0.06717957, -0.06712164,  0.03644813, -0.04640086]),
  'avg_score': np.float64(-0.02553317915142177),
  'feature_names': ('Num_Bathrooms', 'Neighborhood_Quality')},
 22: {'feature_idx': (3, 4),
  'cv_scores': array([-0.08167915, -0.09018765, -0.06913948, -0.00395964, -0.14118459]),
  'avg_score': np.float64(-0.07723010328763244),
  'feature_names': ('Year_Built', 'Lot_Size')},
 23: {'feature_idx': (3, 5),
  'cv_scores': array([-0.18006508, -0.18099409, -0.1811626 , -0.24045258, -0.22367071]),
  'avg_score': np.float64(-0.20126901147787873),
  'feature_names': ('Year_Built', 'Garage_Size')},
 24: {'feature_idx': (3, 6),
  'cv_scores': array([-0.14925693, -0.17082904, -0.21941019, -0.11745594, -0.20147666]),
  'avg_score': np.float64(-0.17168575069901976),
  'feature_names': ('Year_Built', 'Neighborhood_Quality')},
 25: {'feature_idx': (4, 5),
  'cv_scores': array([-0.16812632, -0.03082603, -0.1687897 ,  0.03326652, -0.13764397]),
  'avg_score': np.float64(-0.09442390157787998),
  'feature_names': ('Lot_Size', 'Garage_Size')},
 26: {'feature_idx': (4, 6),
  'cv_scores': array([-0.06084871, -0.09027275, -0.04444556,  0.01587563, -0.11629083]),
  'avg_score': np.float64(-0.059196443664953066),
  'feature_names': ('Lot_Size', 'Neighborhood_Quality')},
 27: {'feature_idx': (5, 6),
  'cv_scores': array([-0.0422382 , -0.01872675, -0.16591066, -0.01176689, -0.02581224]),
  'avg_score': np.float64(-0.052890949861383166),
  'feature_names': ('Garage_Size', 'Neighborhood_Quality')},
 28: {'feature_idx': (0, 1, 2),
  'cv_scores': array([0.98383483, 0.98406728, 0.98585613, 0.98083798, 0.98513513]),
  'avg_score': np.float64(0.9839462687838297),
  'feature_names': ('Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms')},
 29: {'feature_idx': (0, 1, 3),
  'cv_scores': array([0.98829442, 0.98852707, 0.99057907, 0.98936984, 0.98925538]),
  'avg_score': np.float64(0.9892051542451984),
  'feature_names': ('Square_Footage', 'Num_Bedrooms', 'Year_Built')},
 30: {'feature_idx': (0, 1, 4),
  'cv_scores': array([0.98763847, 0.98838528, 0.98847482, 0.98656898, 0.99050194]),
  'avg_score': np.float64(0.9883138969947959),
  'feature_names': ('Square_Footage', 'Num_Bedrooms', 'Lot_Size')},
 31: {'feature_idx': (0, 1, 5),
  'cv_scores': array([0.98270593, 0.98248184, 0.98410025, 0.980933  , 0.98303077]),
  'avg_score': np.float64(0.9826503585095983),
  'feature_names': ('Square_Footage', 'Num_Bedrooms', 'Garage_Size')},
 32: {'feature_idx': (0, 1, 6),
  'cv_scores': array([0.9807716 , 0.98093528, 0.98451155, 0.97609936, 0.9844791 ]),
  'avg_score': np.float64(0.9813593778444545),
  'feature_names': ('Square_Footage', 'Num_Bedrooms', 'Neighborhood_Quality')},
 33: {'feature_idx': (0, 2, 3),
  'cv_scores': array([0.98421757, 0.98666803, 0.9897814 , 0.98520573, 0.98512121]),
  'avg_score': np.float64(0.9861987867202947),
  'feature_names': ('Square_Footage', 'Num_Bathrooms', 'Year_Built')},
 34: {'feature_idx': (0, 2, 4),
  'cv_scores': array([0.9848892 , 0.98552966, 0.98548288, 0.98195507, 0.98757426]),
  'avg_score': np.float64(0.985086211840766),
  'feature_names': ('Square_Footage', 'Num_Bathrooms', 'Lot_Size')},
 35: {'feature_idx': (0, 2, 5),
  'cv_scores': array([0.98127042, 0.97850314, 0.98191819, 0.97985111, 0.98152739]),
  'avg_score': np.float64(0.980614049358221),
  'feature_names': ('Square_Footage', 'Num_Bathrooms', 'Garage_Size')},
 36: {'feature_idx': (0, 2, 6),
  'cv_scores': array([0.97891163, 0.97888414, 0.98111767, 0.9748787 , 0.98098695]),
  'avg_score': np.float64(0.9789558177382951),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Neighborhood_Quality')},
 37: {'feature_idx': (0, 3, 4),
  'cv_scores': array([0.99154276, 0.99218659, 0.99323642, 0.99083192, 0.99268979]),
  'avg_score': np.float64(0.9920974944876768),
  'feature_names': ('Square_Footage', 'Year_Built', 'Lot_Size')},
 38: {'feature_idx': (0, 3, 5),
  'cv_scores': array([0.98411931, 0.98519448, 0.98665001, 0.98672752, 0.98573294]),
  'avg_score': np.float64(0.9856848512538926),
  'feature_names': ('Square_Footage', 'Year_Built', 'Garage_Size')},
 39: {'feature_idx': (0, 3, 6),
  'cv_scores': array([0.98416063, 0.98553993, 0.98795776, 0.98458413, 0.98529973]),
  'avg_score': np.float64(0.9855084369102824),
  'feature_names': ('Square_Footage', 'Year_Built', 'Neighborhood_Quality')},
 40: {'feature_idx': (0, 4, 5),
  'cv_scores': array([0.98382802, 0.98564728, 0.98493995, 0.9828958 , 0.98727369]),
  'avg_score': np.float64(0.9849169471061341),
  'feature_names': ('Square_Footage', 'Lot_Size', 'Garage_Size')},
 41: {'feature_idx': (0, 4, 6),
  'cv_scores': array([0.98372347, 0.98445371, 0.9845231 , 0.98005801, 0.98623672]),
  'avg_score': np.float64(0.9837990022598937),
  'feature_names': ('Square_Footage', 'Lot_Size', 'Neighborhood_Quality')},
 42: {'feature_idx': (0, 5, 6),
  'cv_scores': array([0.97655244, 0.97899936, 0.97834674, 0.97484609, 0.98075548]),
  'avg_score': np.float64(0.9779000219839654),
  'feature_names': ('Square_Footage', 'Garage_Size', 'Neighborhood_Quality')},
 43: {'feature_idx': (1, 2, 3),
  'cv_scores': array([-0.17321966, -0.22828249, -0.21412457, -0.11939685, -0.17905381]),
  'avg_score': np.float64(-0.18281547709323798),
  'feature_names': ('Num_Bedrooms', 'Num_Bathrooms', 'Year_Built')},
 44: {'feature_idx': (1, 2, 4),
  'cv_scores': array([-0.2071041 , -0.08135048, -0.11734242, -0.07010979, -0.12603354]),
  'avg_score': np.float64(-0.12038806654362069),
  'feature_names': ('Num_Bedrooms', 'Num_Bathrooms', 'Lot_Size')},
 45: {'feature_idx': (1, 2, 5),
  'cv_scores': array([-0.10663493, -0.05004281, -0.10409627, -0.12246144, -0.07436902]),
  'avg_score': np.float64(-0.09152089296062668),
  'feature_names': ('Num_Bedrooms', 'Num_Bathrooms', 'Garage_Size')},
 46: {'feature_idx': (1, 2, 6),
  'cv_scores': array([-0.17666947, -0.19434707, -0.38942049, -0.23536325, -0.19552691]),
  'avg_score': np.float64(-0.23826543551536),
  'feature_names': ('Num_Bedrooms', 'Num_Bathrooms', 'Neighborhood_Quality')},
 47: {'feature_idx': (1, 3, 4),
  'cv_scores': array([-0.10180959, -0.07570573, -0.06651516, -0.05757176, -0.18470647]),
  'avg_score': np.float64(-0.09726174085336318),
  'feature_names': ('Num_Bedrooms', 'Year_Built', 'Lot_Size')},
 48: {'feature_idx': (1, 3, 5),
  'cv_scores': array([-0.24076394, -0.21513987, -0.23863845, -0.25691235, -0.27892512]),
  'avg_score': np.float64(-0.24607594592515153),
  'feature_names': ('Num_Bedrooms', 'Year_Built', 'Garage_Size')},
 49: {'feature_idx': (1, 3, 6),
  'cv_scores': array([-0.10198602, -0.24269634, -0.26556067, -0.2091283 , -0.2175609 ]),
  'avg_score': np.float64(-0.20738644632130798),
  'feature_names': ('Num_Bedrooms', 'Year_Built', 'Neighborhood_Quality')},
 50: {'feature_idx': (1, 4, 5),
  'cv_scores': array([-0.25066907, -0.04618825, -0.18423894,  0.006003  , -0.18154087]),
  'avg_score': np.float64(-0.1313268271385322),
  'feature_names': ('Num_Bedrooms', 'Lot_Size', 'Garage_Size')},
 51: {'feature_idx': (1, 4, 6),
  'cv_scores': array([-0.14074364, -0.10392471, -0.12185585, -0.08855124, -0.09183185]),
  'avg_score': np.float64(-0.10938145855782574),
  'feature_names': ('Num_Bedrooms', 'Lot_Size', 'Neighborhood_Quality')},
 52: {'feature_idx': (1, 5, 6),
  'cv_scores': array([-0.31441425, -0.09837519, -0.3605401 , -0.33888175, -0.16225772]),
  'avg_score': np.float64(-0.2548937986847811),
  'feature_names': ('Num_Bedrooms', 'Garage_Size', 'Neighborhood_Quality')},
 53: {'feature_idx': (2, 3, 4),
  'cv_scores': array([-0.1407846 , -0.07197879, -0.06698905,  0.0135372 , -0.16843975]),
  'avg_score': np.float64(-0.08693099807238758),
  'feature_names': ('Num_Bathrooms', 'Year_Built', 'Lot_Size')},
 54: {'feature_idx': (2, 3, 5),
  'cv_scores': array([-0.28935791, -0.28489165, -0.20783315, -0.17107205, -0.20957029]),
  'avg_score': np.float64(-0.23254500947234402),
  'feature_names': ('Num_Bathrooms', 'Year_Built', 'Garage_Size')},
 55: {'feature_idx': (2, 3, 6),
  'cv_scores': array([-0.17826858, -0.27912722, -0.22849514, -0.06211702, -0.12123955]),
  'avg_score': np.float64(-0.1738495022141731),
  'feature_names': ('Num_Bathrooms', 'Year_Built', 'Neighborhood_Quality')},
 56: {'feature_idx': (2, 4, 5),
  'cv_scores': array([-0.15316469, -0.08636781, -0.14682055, -0.01280176, -0.17849851]),
  'avg_score': np.float64(-0.11553066190988726),
  'feature_names': ('Num_Bathrooms', 'Lot_Size', 'Garage_Size')},
 57: {'feature_idx': (2, 4, 6),
  'cv_scores': array([-0.09986914, -0.11423096, -0.05564571,  0.03635926, -0.14024019]),
  'avg_score': np.float64(-0.07472534644265835),
  'feature_names': ('Num_Bathrooms', 'Lot_Size', 'Neighborhood_Quality')},
 58: {'feature_idx': (2, 5, 6),
  'cv_scores': array([-0.14916549, -0.16003221, -0.23853358, -0.0753252 , -0.12476329]),
  'avg_score': np.float64(-0.14956395722293583),
  'feature_names': ('Num_Bathrooms', 'Garage_Size', 'Neighborhood_Quality')},
 59: {'feature_idx': (3, 4, 5),
  'cv_scores': array([-0.09427801, -0.06380989, -0.15939874,  0.00378061, -0.21442231]),
  'avg_score': np.float64(-0.10562566725212172),
  'feature_names': ('Year_Built', 'Lot_Size', 'Garage_Size')},
 60: {'feature_idx': (3, 4, 6),
  'cv_scores': array([-0.03043625, -0.12503398, -0.05518887, -0.01397514, -0.12899278]),
  'avg_score': np.float64(-0.07072540261834623),
  'feature_names': ('Year_Built', 'Lot_Size', 'Neighborhood_Quality')},
 61: {'feature_idx': (3, 5, 6),
  'cv_scores': array([-0.16071317, -0.17882845, -0.27418561, -0.19550264, -0.16063205]),
  'avg_score': np.float64(-0.19397238441460538),
  'feature_names': ('Year_Built', 'Garage_Size', 'Neighborhood_Quality')},
 62: {'feature_idx': (4, 5, 6),
  'cv_scores': array([-0.1301784 , -0.0894378 , -0.20725578, -0.01256104, -0.12991315]),
  'avg_score': np.float64(-0.11386923316223023),
  'feature_names': ('Lot_Size', 'Garage_Size', 'Neighborhood_Quality')},
 63: {'feature_idx': (0, 1, 2, 3),
  'cv_scores': array([0.98919929, 0.98963825, 0.99187165, 0.98955972, 0.99021373]),
  'avg_score': np.float64(0.990096528952425),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Num_Bathrooms',
   'Year_Built')},
 64: {'feature_idx': (0, 1, 2, 4),
  'cv_scores': array([0.98955144, 0.98999305, 0.98897509, 0.9878849 , 0.99166238]),
  'avg_score': np.float64(0.9896133732057519),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Num_Bathrooms',
   'Lot_Size')},
 65: {'feature_idx': (0, 1, 2, 5),
  'cv_scores': array([0.98466831, 0.98317735, 0.9847171 , 0.98227899, 0.98502988]),
  'avg_score': np.float64(0.9839743272326835),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Num_Bathrooms',
   'Garage_Size')},
 66: {'feature_idx': (0, 1, 2, 6),
  'cv_scores': array([0.98389124, 0.98187588, 0.98450139, 0.97804724, 0.98513537]),
  'avg_score': np.float64(0.9826902236810475),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Num_Bathrooms',
   'Neighborhood_Quality')},
 67: {'feature_idx': (0, 1, 3, 4),
  'cv_scores': array([0.99602593, 0.9962045 , 0.99694205, 0.99601247, 0.99610479]),
  'avg_score': np.float64(0.9962579452081888),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Year_Built',
   'Lot_Size')},
 68: {'feature_idx': (0, 1, 3, 5),
  'cv_scores': array([0.98863481, 0.98882364, 0.99001579, 0.99005127, 0.98975066]),
  'avg_score': np.float64(0.9894552364313609),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Year_Built',
   'Garage_Size')},
 69: {'feature_idx': (0, 1, 3, 6),
  'cv_scores': array([0.98879075, 0.98835081, 0.9906769 , 0.98835615, 0.98970031]),
  'avg_score': np.float64(0.9891749841989587),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Year_Built',
   'Neighborhood_Quality')},
 70: {'feature_idx': (0, 1, 4, 5),
  'cv_scores': array([0.98878917, 0.98918233, 0.98821656, 0.98787127, 0.99028916]),
  'avg_score': np.float64(0.9888696958736842),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Lot_Size',
   'Garage_Size')},
 71: {'feature_idx': (0, 1, 4, 6),
  'cv_scores': array([0.98892199, 0.98782812, 0.98795666, 0.9858631 , 0.99033529]),
  'avg_score': np.float64(0.9881810327785461),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Lot_Size',
   'Neighborhood_Quality')},
 72: {'feature_idx': (0, 1, 5, 6),
  'cv_scores': array([0.98226917, 0.98140009, 0.98305885, 0.97822351, 0.98348323]),
  'avg_score': np.float64(0.9816869725513051),
  'feature_names': ('Square_Footage',
   'Num_Bedrooms',
   'Garage_Size',
   'Neighborhood_Quality')},
 73: {'feature_idx': (0, 2, 3, 4),
  'cv_scores': array([0.99287311, 0.99283447, 0.99381508, 0.99240987, 0.99351533]),
  'avg_score': np.float64(0.9930895738829442),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Year_Built',
   'Lot_Size')},
 74: {'feature_idx': (0, 2, 3, 5),
  'cv_scores': array([0.9858341 , 0.98688761, 0.98766762, 0.98700783, 0.98619648]),
  'avg_score': np.float64(0.9867187282609786),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Year_Built',
   'Garage_Size')},
 75: {'feature_idx': (0, 2, 3, 6),
  'cv_scores': array([0.98579474, 0.98647979, 0.98875575, 0.98449396, 0.98657252]),
  'avg_score': np.float64(0.9864193536700702),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Year_Built',
   'Neighborhood_Quality')},
 76: {'feature_idx': (0, 2, 4, 5),
  'cv_scores': array([0.98512172, 0.98589791, 0.98445628, 0.98422384, 0.98758023]),
  'avg_score': np.float64(0.9854559945104331),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Lot_Size',
   'Garage_Size')},
 77: {'feature_idx': (0, 2, 4, 6),
  'cv_scores': array([0.98529034, 0.98458236, 0.98482525, 0.9814917 , 0.98686158]),
  'avg_score': np.float64(0.9846102471647284),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Lot_Size',
   'Neighborhood_Quality')},
 78: {'feature_idx': (0, 2, 5, 6),
  'cv_scores': array([0.97999946, 0.97750631, 0.97968924, 0.97756294, 0.98185052]),
  'avg_score': np.float64(0.9793216952814756),
  'feature_names': ('Square_Footage',
   'Num_Bathrooms',
   'Garage_Size',
   'Neighborhood_Quality')},
 79: {'feature_idx': (0, 3, 4, 5),
  'cv_scores': array([0.99198923, 0.99200599, 0.99288562, 0.99151348, 0.99311621]),
  'avg_score': np.float64(0.9923021041222535),
  'feature_names': ('Square_Footage',
   'Year_Built',
   'Lot_Size',
   'Garage_Size')},
 80: {'feature_idx': (0, 3, 4, 6),
  'cv_scores': array([0.99113084, 0.99166147, 0.99213859, 0.99045157, 0.99288342]),
  'avg_score': np.float64(0.991653178172534),
  'feature_names': ('Square_Footage',
   'Year_Built',
   'Lot_Size',
   'Neighborhood_Quality')},
 81: {'feature_idx': (0, 3, 5, 6),
  'cv_scores': array([0.98511221, 0.98614715, 0.98560705, 0.98516448, 0.98553668]),
  'avg_score': np.float64(0.9855135134598774),
  'feature_names': ('Square_Footage',
   'Year_Built',
   'Garage_Size',
   'Neighborhood_Quality')},
 82: {'feature_idx': (0, 4, 5, 6),
  'cv_scores': array([0.9840892 , 0.98441568, 0.983104  , 0.98262781, 0.98683826]),
  'avg_score': np.float64(0.9842149918787172),
  'feature_names': ('Square_Footage',
   'Lot_Size',
   'Garage_Size',
   'Neighborhood_Quality')},
 83: {'feature_idx': (1, 2, 3, 4),
  'cv_scores': array([-0.15227751, -0.10049154, -0.08382777, -0.06471026, -0.19268642]),
  'avg_score': np.float64(-0.11879869825873417),
  'feature_names': ('Num_Bedrooms',
   'Num_Bathrooms',
   'Year_Built',
   'Lot_Size')},
 84: {'feature_idx': (1, 2, 3, 5),

# Pipeline

## Pipeline as transformer

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

In [35]:
simple_imputer = SimpleImputer(strategy='mean')
scaler = MinMaxScaler()

In [36]:
pipe = Pipeline(steps=[('imputer', simple_imputer), ('scaler', scaler)])

In [37]:
pipe.fit(X_train)

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', MinMaxScaler())])

In [38]:
pipe.transform(X_test)

array([[0.78047153, 0.5       , 0.        , ..., 0.35394383, 0.5       ,
        0.44444444],
       [0.40191281, 0.5       , 0.        , ..., 0.19116336, 0.5       ,
        0.33333333],
       [0.9352758 , 0.        , 1.        , ..., 0.28576267, 0.5       ,
        0.77777778],
       ...,
       [0.88701068, 0.75      , 0.5       , ..., 0.64467318, 0.        ,
        0.33333333],
       [0.301379  , 0.        , 0.        , ..., 0.90109175, 1.        ,
        0.77777778],
       [0.59875445, 0.        , 0.        , ..., 0.75955225, 1.        ,
        0.        ]], shape=(200, 7))

## Pipeline as model

In [39]:
model = LinearRegression()

In [40]:
pipe = Pipeline(steps=[('imputer', simple_imputer), ('scaler', scaler), ('model', model)])

In [41]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', MinMaxScaler()),
                ('model', LinearRegression())])

In [42]:
metrics(y_test, pipe.predict(X_test))

R2: 0.9984263636823413
MAE: 8174.5836000066365
RMSE: 10071.48442413709

## Обработка разнородных данных

In [78]:
df = pd.read_csv('insurance.csv')

In [79]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [80]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['charges'], axis=1), df['charges'], test_size=0.2, random_state=42)

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [81]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [86]:
col_transformer = ColumnTransformer([('num_preproc', MinMaxScaler(), [x for x in X_train.columns if X_train[x].dtype!='str']),
                                     ('cat_preproc', OneHotEncoder(dtype='int'), [x for x in X_train.columns if X_train[x].dtype=='str'])])

In [87]:
pipe = Pipeline([('preproc', col_transformer), ('LR', LinearRegression())])

In [88]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preproc',
                 ColumnTransformer(transformers=[('num_preproc', MinMaxScaler(),
                                                  ['age', 'bmi', 'children']),
                                                 ('cat_preproc',
                                                  OneHotEncoder(dtype='int'),
                                                  ['sex', 'smoker',
                                                   'region'])])),
                ('LR', LinearRegression())])

In [89]:
metrics(y_test, pipe.predict(X_test))

R2: 0.7835929767120723
MAE: 4181.194473753648
RMSE: 5796.2846592762735

## Подбор гиперпараметров

In [90]:
from sklearn.model_selection import GridSearchCV

In [91]:
pipe = Pipeline([('preproc', col_transformer), ('CatBoost', CatBoostRegressor(verbose=False))])

In [92]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preproc',
                 ColumnTransformer(transformers=[('num_preproc', MinMaxScaler(),
                                                  ['age', 'bmi', 'children']),
                                                 ('cat_preproc',
                                                  OneHotEncoder(dtype='int'),
                                                  ['sex', 'smoker',
                                                   'region'])])),
                ('CatBoost',
                 CatBoostRegressor(loss_function='RMSE', verbose=False))])

In [93]:
pipe.score(X_test, y_test)

np.float64(0.8650932224197827)

In [94]:
param_grid = {
    "CatBoost__iterations": [1000, 2000],
    "CatBoost__learning_rate": [0.01, 0.05],
    "CatBoost__depth": [3, 5, 7]
}
search = GridSearchCV(pipe, param_grid)

In [95]:
search.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('preproc',
                                        ColumnTransformer(transformers=[('num_preproc',
                                                                         MinMaxScaler(),
                                                                         ['age',
                                                                          'bmi',
                                                                          'children']),
                                                                        ('cat_preproc',
                                                                         OneHotEncoder(dtype='int'),
                                                                         ['sex',
                                                                          'smoker',
                                                                          'region'])])),
                                       ('CatBoost',
                                        CatBoostRegressor(loss_function='RMSE', verbose=False))]),
             param_grid={'CatBoost__depth': [3, 5, 7],
                         'CatBoost__iterations': [1000, 2000],
                         'CatBoost__learning_rate': [0.01, 0.05]})

In [96]:
search.best_score_

np.float64(0.8508020663055372)

In [97]:
search.best_params_

{'CatBoost__depth': 3,
 'CatBoost__iterations': 1000,
 'CatBoost__learning_rate': 0.01}